from ex_8 import print_error

print_error("")
